### ISSUE TITLE
ArangoDB.Client.ArangoServerException: invalid document type.

### ISSUE THREAD

**Issue by ma3yta** [OrleansContrib/Orleans.StorageProvider.Arango#4]
Arango Server: 3.3.3 [win64] storage engine: rocksdb
Orleans version: 1.5.2.0 (Release).
.NET version: 4.0.30319.42000
OS version: Microsoft Windows NT 6.2.9200.0

Stacktrace:
```
invalid document type. ErrorNumber: 1227 HttpStatusCode: 400
Exception = ArangoDB.Client.ArangoServerException: invalid document type. ErrorNumber: 1227 HttpStatusCode: 400
   at ArangoDB.Client.BaseResultAnalyzer.ThrowIfNeeded(BaseResult baseResult)
   at ArangoDB.Client.Http.HttpCommand.<RequestMergedResult>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArangoDB.Client.Collection.ArangoCollection.<InsertAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Orleans.StorageProvider.Arango.ArangoStorageProvider.<WriteStateAsync>d__20.MoveNext()

[2018-02-24 18:05:20.985 GMT     4      ERROR   190001  ArangoStorageProvider   172.29.47.129:0]    !!!!!!!!!! ArangoStorageProvider.WriteStateAsync()
Exc level 0: ArangoDB.Client.ArangoServerException: invalid document type. ErrorNumber: 1227 HttpStatusCode: 400
   at ArangoDB.Client.BaseResultAnalyzer.ThrowIfNeeded(BaseResult baseResult)
   at ArangoDB.Client.Http.HttpCommand.<RequestMergedResult>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArangoDB.Client.Collection.ArangoCollection.<InsertAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Orleans.StorageProvider.Arango.ArangoStorageProvider.<WriteStateAsync>d__20.MoveNext()
ArangoDB.Client.ArangoServerException: invalid document type. ErrorNumber: 1227 HttpStatusCode: 400
   at ArangoDB.Client.BaseResultAnalyzer.ThrowIfNeeded(BaseResult baseResult)
   at ArangoDB.Client.Http.HttpCommand.<RequestMergedResult>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArangoDB.Client.Collection.ArangoCollection.<InsertAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Orleans.StorageProvider.Arango.ArangoStorageProvider.<WriteStateAsync>d__20.MoveNext()
Exception = Orleans.StorageProvider.Arango.ArangoStorageException: ArangoDB.Client.ArangoServerException: invalid document type. ErrorNumber: 1227 HttpStatusCode: 400
   at ArangoDB.Client.BaseResultAnalyzer.ThrowIfNeeded(BaseResult baseResult)
   at ArangoDB.Client.Http.HttpCommand.<RequestMergedResult>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArangoDB.Client.Collection.ArangoCollection.<InsertAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Orleans.StorageProvider.Arango.ArangoStorageProvider.<WriteStateAsync>d__20.MoveNext()
   at Orleans.StorageProvider.Arango.ArangoStorageProvider.<WriteStateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Core.GrainStateStorageBridge.<WriteStateAsync>d__7.MoveNext()

[2018-02-24 18:05:21.079 GMT    14      ERROR   102203  ArangoStorageProvider   172.29.47.129:0]    !!!!!!!!!! Error from storage provider during WriteState for grain Type=ni.grainClasses.DeviceGrain Pk=*grn/1DB5468E/00000000000000000000000000000000030000001db5468e-0x7FBADA0D Id=GrainReference:*grn/1DB5468E/00000000 Error=

Exc level 0: Orleans.StorageProvider.Arango.ArangoStorageException: ArangoDB.Client.ArangoServerException: invalid document type. ErrorNumber: 1227 HttpStatusCode: 400
   at ArangoDB.Client.BaseResultAnalyzer.ThrowIfNeeded(BaseResult baseResult)
   at ArangoDB.Client.Http.HttpCommand.<RequestMergedResult>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArangoDB.Client.Collection.ArangoCollection.<InsertAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Orleans.StorageProvider.Arango.ArangoStorageProvider.<WriteStateAsync>d__20.MoveNext()
   at Orleans.StorageProvider.Arango.ArangoStorageProvider.<WriteStateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Core.GrainStateStorageBridge.<WriteStateAsync>d__7.MoveNext()
Exc level 0: Orleans.StorageProvider.Arango.ArangoStorageException: ArangoDB.Client.ArangoServerException: invalid document type. ErrorNumber: 1227 HttpStatusCode: 400
   at ArangoDB.Client.BaseResultAnalyzer.ThrowIfNeeded(BaseResult baseResult)
   at ArangoDB.Client.Http.HttpCommand.<RequestMergedResult>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArangoDB.Client.Collection.ArangoCollection.<InsertAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Orleans.StorageProvider.Arango.ArangoStorageProvider.<WriteStateAsync>d__20.MoveNext()
   at Orleans.StorageProvider.Arango.ArangoStorageProvider.<WriteStateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Core.GrainStateStorageBridge.<WriteStateAsync>d__7.MoveNext()
```

**Comment by richorama** [comment]
thanks for reporting this, I'll take a look into it shortly.
